trigger:
- main

pool:
  name: agent-java

steps:
- checkout: self

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'ado-agent-service-connection2'
    namespace: 'default'
    command: 'apply'
    arguments: '-f agent-java-keda.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    outputFormat: 'none'
