apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-devops-auth-trigger
spec:
  secretTargetRef:
  - parameter: personalAccessToken
    name: azure-devops-pat
    key: AZP_TOKEN
  - parameter: organizationURL
    name: azure-devops-url
    key: AZP_URL

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-devops-scaledobject
spec:
  scaleTargetRef:
    name: agent-java-deployment
  minReplicaCount: 3   
  maxReplicaCount: 5 
  triggers:
  - type: azure-devops
    metadata:
      organizationURLFromEnv: AZP_URL
      personalAccessTokenFromEnv: AZP_TOKEN
      poolID: 'agent-java'
    authenticationRef:
      name: azure-devops-auth-trigger
